### PR TITLE
removed period from example -- domain.tld returns w/out a period.

### PR DESCRIPTION
**Pull request by binarymason**

### CODE REVIEW

**Comment by benbalter** [comment]
Nice catch. Thanks @m8ss!

**Comment by m8ss** [comment]
Glad to help.  Very helpful tool!

**Comment by benbalter** [comment]
Awesome to hear. Can I ask what you're using the Gem for?

**Comment by m8ss** [comment]
[To blacklist tlds.](https://github.com/m8ss/rverr/blob/dev/lib/rverr/harvest/blacklist.rb#L6-L33)

I'm working on a project that (for right now) uses Google Dorks to find SQL injection vulnerable sites and will crawl for a contact email to notify the owner.  At least during development, I don't want to send large amounts of automated traffic to certain sites.

The dream is for a free, open-source notification system for vulnerabilities.

**Comment by benbalter** [comment]
Woah, nice.

/cc @leereilly who wrote the first iteration of the core of this Gem as Swot.

**Pull request merged**
